export const actionTypes = {
    LIST_PRODUCTS: "LIST_PRODUCTS",
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    SELECT_PRODUCT: "SELECT_PRODUCT",
    REMOVE_SELECT_PRODUCT: "REM0VE_SELECT_PRODUCT",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_ITEM: "REMOVE_ITEM",
    REMOVE_ALL_ITEM: "REMOVE_ALL_ITEM",
    TOTAL_PRODUCT: "TOTAL_PRODUCT",
    INCREASE_ITEM: "INCREASE_ITEM",
    DECREASE_ITEM: "DECREASE_ITEM",
    LOGIN: "LOGIN",
    PAYMENT: "PAYMENT",
    CREATE_ORDER: "CREATE_ORDER",
    CLEAR_CART: "CLEAR_CART",
    CLEAR_ORDER: "CLEAR_ORDER",
    FETCH_ORDERS: "FETCH_ORDERS",
    GET_USER: "GET_USER"

}